global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-todo-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']