version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-todolist
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - todolist-network

  backend:
    build: ./backend
    container_name: backend-todolist
    restart: always
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/todolist?authSource=admin
      PORT: 3001
    depends_on:
      - mongodb
    networks:
      - todolist-network

  frontend:
    build: ./frontend
    container_name: frontend-todolist
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:3001
    depends_on:
      - backend
    networks:
      - todolist-network

volumes:
  mongodb_data:

networks:
  todolist-network:
    driver: bridge